/**
 * Supervised training launch (issue #15).
 *
 * Incident (2026-09-17): a training run died the moment its tmux session was reused, and
 * nobody noticed for 14.5 hours of billed idle time. The queue was fine; what was missing
 * was any way to ask "is this alive?" without six SSH calls.
 *
 * The generated script runs the training command with a watchdog beside it and keeps one
 * status file that answers the whole question in a single read:
 *
 *   RUNNING <label> epoch=7/30 gpu=100% idle=0min <ts>
 *   ALERT   idle 47min - log has not moved | <label> epoch=7/30 gpu=0% <ts>
 *   DONE    <label> rc=0 elapsed=29449s <ts>
 *   FAILED  <label> rc=1 elapsed=12s - tail <log> <ts>
 *
 * Ported from PIU-v2 `scripts/pod_fold_runner.sh` (branch worktree-segmentation), including
 * the bug it was fixed for — see the zombie note on the generated script below.
 */

export interface SupervisedScriptOptions {
  /** The training command, run from workingDir. */
  command: string;
  /** Absolute path on the pod for the single status file. */
  statusPath: string;
  /** Absolute path on the pod for the training log. */
  logPath: string;
  /** Shown in status lines so one file can be attributed to a run. */
  label?: string;
  /** Minutes without log growth before the status flips to ALERT. */
  idleAlertMinutes?: number;
  /** Directory to run the command from. */
  workingDir?: string;
  /** If this path already exists, report DONE and skip — makes a relaunch idempotent. */
  skipIfExists?: string;
  /** Extracted into `epoch=` in the status line. */
  progressPattern?: string;
  /** Rendered as the denominator of `epoch=`. */
  totalSteps?: number;
}

export interface StatusLine {
  state: "RUNNING" | "ALERT" | "DONE" | "FAILED";
  idleMinutes: number | null;
  gpuUtil: number | null;
  exitCode: number | null;
  raw: string;
}

/**
 * Single quotes would terminate the shell quoting the script wraps values in. Reject rather
 * than escape: a silently mangled training command is worse than a refusal at build time.
 */
function assertNoSingleQuote(value: string, field: string): void {
  if (value.includes("'")) {
    throw new Error(
      `${field} must not contain a single quote (got: ${value}). Put the quoted part in a script file on the pod and call that instead.`
    );
  }
}

export function buildSupervisedScript(options: SupervisedScriptOptions): string {
  const {
    command,
    statusPath,
    logPath,
    label = "run",
    idleAlertMinutes = 25,
    workingDir = "/workspace",
    skipIfExists,
    progressPattern = "Epoch [0-9]+",
    totalSteps,
  } = options;

  assertNoSingleQuote(command, "command");
  for (const [field, value] of Object.entries({ statusPath, logPath, label, workingDir, progressPattern })) {
    assertNoSingleQuote(String(value), field);
  }
  if (skipIfExists) assertNoSingleQuote(skipIfExists, "skipIfExists");

  const total = totalSteps ? String(totalSteps) : "?";

  const skipBlock = skipIfExists
    ? `
if [ -e '${skipIfExists}' ]; then
  echo "DONE ${label} (already complete, skipped) $(date -Is)" > "$STATUS"
  exit 0
fi
`
    : "";

  return `#!/bin/bash
# Generated by runpod-mcp launch_supervised_training. Runs one job with a watchdog that keeps
# the whole state in "$STATUS", so one read replaces a round of SSH questions.
set -u

STATUS='${statusPath}'
LOG='${logPath}'
IDLE_ALERT_MIN=${idleAlertMinutes}

mkdir -p "$(dirname "$STATUS")" "$(dirname "$LOG")"
cd '${workingDir}' || { echo "FAILED ${label} rc=1 - no such directory ${workingDir} $(date -Is)" > "$STATUS"; exit 1; }
${skipBlock}
T0=$SECONDS
echo "RUNNING ${label} starting $(date -Is)" > "$STATUS"

${command} > "$LOG" 2>&1 &
TRAIN_PID=$!

# The watchdog is its own process and the main shell waits on training directly.
# An earlier version polled \`kill -0\` from the main shell: that succeeds on a zombie
# (exited but unreaped) child, so when training died the loop spun forever and STATUS
# never left "starting" — the watchdog failed in exactly the case it existed for.
# \`wait\` reaps, so the main shell learns the truth the moment the process ends.
(
  while :; do
    sleep 60
    ps -p "$TRAIN_PID" >/dev/null 2>&1 || exit 0
    case "$(ps -o stat= -p "$TRAIN_PID" 2>/dev/null | tr -d ' ')" in Z*) exit 0;; esac
    NOW=$(date +%s)
    MTIME=$(stat -c %Y "$LOG" 2>/dev/null || echo "$NOW")
    IDLE_MIN=$(( (NOW - MTIME) / 60 ))
    GPU=$(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader 2>/dev/null | head -1 | tr -d ' %')
    STEP=$(grep -oE '${progressPattern}' "$LOG" 2>/dev/null | tail -1 | grep -oE '[0-9]+')
    if [ "$IDLE_MIN" -ge "$IDLE_ALERT_MIN" ]; then
      echo "ALERT idle \${IDLE_MIN}min - log has not moved | ${label} epoch=\${STEP:-?}/${total} gpu=\${GPU:-?}% $(date -Is)" > "$STATUS"
    else
      echo "RUNNING ${label} epoch=\${STEP:-0}/${total} gpu=\${GPU:-?}% idle=\${IDLE_MIN}min $(date -Is)" > "$STATUS"
    fi
  done
) &
WATCHDOG_PID=$!

wait "$TRAIN_PID"; RC=$?
kill "$WATCHDOG_PID" 2>/dev/null
wait "$WATCHDOG_PID" 2>/dev/null
ELAPSED=$((SECONDS-T0))
if [ "$RC" -eq 0 ]; then
  echo "DONE ${label} rc=0 elapsed=\${ELAPSED}s $(date -Is)" > "$STATUS"
else
  echo "FAILED ${label} rc=$RC elapsed=\${ELAPSED}s - tail $LOG $(date -Is)" > "$STATUS"
  tail -30 "$LOG"
fi
exit "$RC"
`;
}

/** Parse one STATUS line into its fields. Returns null for an empty or unrecognized line. */
export function parseStatusLine(line: string): StatusLine | null {
  const raw = line.trim();
  const state = raw.split(/\s+/)[0];
  if (state !== "RUNNING" && state !== "ALERT" && state !== "DONE" && state !== "FAILED") {
    return null;
  }

  const idleMatch = raw.match(/idle[= ](\d+)min/);
  const gpuMatch = raw.match(/gpu=(\d+)%/);
  const rcMatch = raw.match(/\brc=(-?\d+)/);

  return {
    state,
    idleMinutes: idleMatch ? parseInt(idleMatch[1], 10) : null,
    gpuUtil: gpuMatch ? parseInt(gpuMatch[1], 10) : null,
    exitCode: rcMatch ? parseInt(rcMatch[1], 10) : null,
    raw,
  };
}
